#!/usr/bin/env bash
# Installs nginx on a web server and redirects
sudo apt-get update
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee "/var/www/html/index.html"
command="\\\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
# set permanent redirect using command
sudo sed -i "/server_name _;/a $command" /etc/nginx/sites-available/default
sudo service nginx restart
