#!/usr/bin/env bash
# Installs nginx on web server, set content and redirect
sudo apt-get update
sudo apt-get install nginx -y
# Set content
echo "Hello World" | sudo tee "/var/www/html/index.html"
# Set redirect
new_str="\\\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _;/a $new_str" /etc/nginx/sites-available/default
# Simple 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sms_404="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "49i $sms_404" /etc/nginx/sites-available/default
sudo sed -i "42i \\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
sudo service nginx restart
