#!/usr/bin/env bash
# Install and configure a load balancer on server lb-01
sudo apt update
sudo apt install haproxy -y
sudo sed -i '$ aENABLED=1' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo -e "\nfrontend first_lb\n\tbind *:80\n\tmode http\n\tdefault_backend webservers\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend webservers\n\tbalance roundrobin\n\tserver 2590-web-01 34.138.77.188:80 check\nserver 2590-web-02 3.84.197.253:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
