#!/usr/bin/env bash
# Generate a MySQL dump and create compressed archive
if [[ $# -lt 1 ]]; then
    echo "USAGE: $1 <password>"
else
    dump='backup.sql'
    mysqldump -uroot -p"$1" --all-databases > "$dump"
    tar_out="$(date +%d-%m-%Y.tar.gz)"
    tar -czf "$tar_out" "$dump"
fi
