#!/usr/bin/env bash
# Make inf loop to print forever, adv task
file="/var/run/holbertonscript.pid"
echo $$ > "$file"
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$file"; exit' SIGQUIT
i=0
while [ $i -lt 1 ]; do
	echo "To infinity and beyond"
	sleep 2
done
